# Default values for hello.

replicaCount: 1
logLevel: info

image:
  repository: point1304/hello-server
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: NodePort
  httpPort: 8000
  externalPort: 8000
  nodePort: 31198

resources:
  requests:
    cpu: 10m
    memory: 32Mi

nodeSelector: {}
