# Default values for hello.

replicaCount: 1
logLevel: info

image:
  repository: point1304/hello-server
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  httpPort: 8000

resources:
  requests:
    cpu: 1m
    memory: 16Mi

nodeSelector: {}
