# Default values for hello.

replicaCount: 4
logLevel: info

image:
  repository: point1304/hello-server
  tag: 0.1.2
  pullPolicy: Always

service:
  enabled: true
  type: ClusterIP
  httpPort: 8080
  externalPort: 8080
  nodePort: 31198

resources:
  requests:
    cpu: 10m
    memory: 32Mi

nodeSelector: {}
