# Default values for hello.

replicaCount: 4
logLevel: info

image:
  repository: point1304/hello-server
  tag: 0.1.2
  pullPolicy: IfNotPresent

service:
  enabled: true
  httpPort: 8000
  externalPort: 8000
  firstNodePort: 31198

resources:
  requests:
    cpu: 10m
    memory: 32Mi

nodeSelector: {}
